### ISSUE TITLE
Issue with RBAC

### ISSUE THREAD

**Issue by LucaPrete** [SparebankenVest/public-helm-charts#7]
Hi guys,

First of all, great work! We've been using this for quite a while and we find it fantastic!

We've recently secured helm, following the best-practices described on their website (basically TLS + RBAC - limiting the tiller SA to do certain operations only in certain namespaces).

Unfortunately, this seems to conflict with the ClusterRole that this helm-chart (as I guess many others do...) needs to create. When I try to install the injector with:

```
helm install spv-charts/azure-key-vault-env-injector \
  -n key-vault-env-injector \
  --set installCrd=false \
  --tiller-namespace tiller
  --tls
```

I get:

```
Error: release key-vault-env-injector failed: clusterroles.rbac.authorization.k8s.io is forbidden: User "system:serviceaccount:tiller:tiller" cannot create resource "clusterroles" in API group "rbac.authorization.k8s.io" at the cluster scope
``` 

I was wondering if you could have any suggestions...

Thanks,

-Luca

**Comment by LucaPrete** [comment]
For now, I've ended up using `helm template` and installing everything with kubectl... ;)

**Comment by torresdal** [comment]
Hi @LucaPrete - thanks for reporting this. I haven't had a chance to verify the issue your having, and I'm not sure if we're going to - taking into account that the requirement for tiller disappeared with Helm 3. I'm aware that it will still take some time for everyone to move to helm 3, so if this issue is pressing, we're happy to accept any pull requests that fixes this.

**Comment by torresdal** [comment]
Please repopen this if you think this is something we really should fix.
